#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Bundle a marimo notebook plus the local `rsmodel` package into one file.

molab (https://molab.marimo.io) resolves dependencies from PyPI via `uv`; it
cannot follow the `[tool.uv.sources]` path override that points at ../rsmodel.
This script inlines the package sources into a `with app.setup:` block that
registers them in `sys.modules`, so every `import rsmodel` in the notebook body
keeps working unchanged. The result is a single self-contained .py file.

Usage:
    uv run tools/build_molab.py                      # default notebook
    uv run tools/build_molab.py notebooks/foo.py -o out.py
    uv run tools/build_molab.py --check              # CI: fail if stale
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG_DIR = ROOT / "rsmodel" / "rsmodel"

# Order matters: dependencies of a module must be registered before it.
MODULES = ["core", "utils", "analysis", "__init__"]

DEFAULT_NOTEBOOK = ROOT / "notebooks" / "interactive_playground.py"
DEFAULT_OUTPUT = ROOT / "molab" / "interactive_playground_molab.py"

HEADER_RE = re.compile(r"\A# /// script\n.*?^# ///\n", re.DOTALL | re.MULTILINE)
APP_RE = re.compile(r"^app = marimo\.App\((.*?)\)\n", re.DOTALL | re.MULTILINE)
RUNCOMMENT_RE = re.compile(r"\A\s*(?:^#[^\n]*\n)+\s*(?=import marimo\n)", re.MULTILINE)
SETUP_RE = re.compile(r"^with app\.setup:\n", re.MULTILINE)
LAYOUT_RE = re.compile(r"^\s*layout_file=.*?,?\n", re.MULTILINE)


def read_header(text: str) -> tuple[str, str]:
    """Split PEP 723 script metadata off the front of the notebook."""
    m = HEADER_RE.match(text)
    if not m:
        sys.exit("error: no PEP 723 header found in notebook")
    return m.group(0), text[m.end() :]


def rewrite_header(header: str) -> str:
    """Drop the rsmodel dependency and the local path source."""
    lines = header.splitlines(keepends=True)
    out, in_sources = [], False
    for line in lines:
        stripped = line.lstrip("# ").rstrip()
        if stripped.startswith("[tool.uv.sources]"):
            in_sources = True
            continue
        if in_sources:
            if stripped.startswith("rsmodel"):
                continue
            if stripped.startswith("["):
                in_sources = False
            elif stripped in ("", "///"):
                if stripped == "///":
                    in_sources = False
                else:
                    continue
        if re.fullmatch(r'#\s*"rsmodel[^"]*",\s*', line.rstrip("\n")):
            continue
        out.append(line)
    # collapse the blank comment lines the removals leave behind
    text = "".join(out)
    text = re.sub(r"(#\n)+(# ///)", r"\2", text)
    return text


def embed(name: str, source: str) -> str:
    """Render one module source as a dict entry, keeping it human-readable."""
    if "'''" in source:
        sys.exit(f"error: {name} contains ''' — the r''' embedding is unsafe")
    if source.rstrip("\n").endswith("\\"):
        sys.exit(f"error: {name} ends with a backslash — invalid in a raw string")
    return f"    {name!r}: r'''\n{source}''',\n"


def build_setup_block(notebook_name: str) -> str:
    """Produce the `with app.setup:` block that vendors the package."""
    entries = "".join(
        embed(n, (PKG_DIR / f"{n}.py").read_text(encoding="utf-8")) for n in MODULES
    )
    return f'''with app.setup:
    # --- vendored rsmodel package (generated by tools/build_molab.py) ---
    # Do not edit here. Edit rsmodel/rsmodel/*.py and regenerate:
    #     uv run tools/build_molab.py
    # Source notebook: {notebook_name}
    import sys as _sys
    import types as _types

    _RSMODEL_SOURCES = {{
{entries}    }}

    def _install_rsmodel(sources, package="rsmodel"):
        """Register the inlined sources as an importable package."""
        pkg = _types.ModuleType(package)
        pkg.__path__ = []  # marks it as a package so relative imports resolve
        pkg.__package__ = package
        _sys.modules[package] = pkg
        for name in sources:
            if name == "__init__":
                continue
            mod = _types.ModuleType(f"{{package}}.{{name}}")
            mod.__package__ = package
            _sys.modules[f"{{package}}.{{name}}"] = mod
            exec(compile(sources[name], f"<{{package}}/{{name}}.py>", "exec"), mod.__dict__)
            setattr(pkg, name, mod)
        exec(
            compile(sources["__init__"], f"<{{package}}/__init__.py>", "exec"),
            pkg.__dict__,
        )
        return pkg

    if "rsmodel" not in _sys.modules:
        _install_rsmodel(_RSMODEL_SOURCES)
    # --- end vendored rsmodel ---

'''


def build(notebook: Path, keep_layout: bool = False) -> str:
    text = notebook.read_text(encoding="utf-8")
    header, body = read_header(text)
    header = rewrite_header(header)
    # the source notebook's "how to run locally" comment does not apply here
    body = RUNCOMMENT_RE.sub("", body)

    if SETUP_RE.search(body):
        sys.exit(
            "error: notebook already has a `with app.setup:` block; "
            "merge by hand or extend this script"
        )

    m = APP_RE.search(body)
    if not m:
        sys.exit("error: could not locate the `app = marimo.App(...)` statement")

    app_stmt = m.group(0)
    if not keep_layout:
        # layouts/*.json is not uploaded to molab; a dangling reference breaks the app
        app_stmt = LAYOUT_RE.sub("", app_stmt)
        app_stmt = re.sub(r",(\s*)\)", r"\1)", app_stmt)

    banner = (
        "# GENERATED FILE — do not edit.\n"
        f"# Built from {notebook.relative_to(ROOT)} by tools/build_molab.py.\n"
        "# Self-contained single-file build for https://molab.marimo.io\n"
        "\n"
    )
    setup = build_setup_block(str(notebook.relative_to(ROOT)))
    return header + banner + body[: m.start()] + app_stmt + "\n" + setup + body[m.end() :]


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("notebook", nargs="?", type=Path, default=DEFAULT_NOTEBOOK)
    p.add_argument("-o", "--output", type=Path, default=None)
    p.add_argument("--keep-layout", action="store_true", help="keep layout_file=...")
    p.add_argument("--check", action="store_true", help="fail if output is stale")
    args = p.parse_args()

    out = args.output or (
        DEFAULT_OUTPUT
        if args.notebook == DEFAULT_NOTEBOOK
        else ROOT / "molab" / f"{args.notebook.stem}_molab.py"
    )
    new = build(args.notebook, keep_layout=args.keep_layout)

    if args.check:
        if not out.exists():
            print(f"{out} is missing", file=sys.stderr)
            return 1
        old = out.read_text(encoding="utf-8")
        if old != new:
            sys.stderr.writelines(
                difflib.unified_diff(
                    old.splitlines(True), new.splitlines(True), "committed", "rebuilt"
                )
            )
            print(f"\n{out} is stale — run: uv run tools/build_molab.py", file=sys.stderr)
            return 1
        print(f"{out} is up to date")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(new, encoding="utf-8")
    print(f"wrote {out} ({len(new.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
