#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["marimo>=0.23"]
# ///
"""Publish a marimo notebook as a self-contained WebAssembly site.

One command turns notebooks/interactive_playground.py into a static folder that
runs entirely in the browser — no Python, no server, no backend:

    uv run tools/export_playground.py            # -> build/site/
    uv run tools/export_playground.py --serve    # ...and preview it locally

Three things happen, in order:

1. Bundle.  The local `rsmodel` package is inlined into a `with app.setup:` block
   that registers it in `sys.modules`, so the notebook's `import rsmodel` works
   with nothing installed. Pyodide has no access to this repo, so vendoring is
   what makes the notebook portable.
2. Export.  `marimo export html-wasm --mode run --no-show-code` renders the
   bundle into a static site. The slides layout is written as a sibling .json so
   marimo's own inline_layout_file() folds it into index.html.
3. Verify.  index.html is parsed back and checked: run mode, code hidden, slides
   layout present with one entry per cell, rsmodel actually embedded. A silent
   half-broken export is worse than a loud failure.
"""

from __future__ import annotations

import argparse
import base64
import functools
import http.server
import json
import re
import shutil
import socketserver
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG_DIR = ROOT / "rsmodel" / "rsmodel"

# Order matters: a module must be registered before anything that imports it.
MODULES = ["core", "utils", "analysis", "__init__"]

DEFAULT_NOTEBOOK = ROOT / "notebooks" / "interactive_playground.py"
DEFAULT_OUTPUT = ROOT / "build" / "site"

HEADER_RE = re.compile(r"\A# /// script\n.*?^# ///\n", re.DOTALL | re.MULTILINE)
APP_RE = re.compile(r"^app = marimo\.App\((.*?)\)\n", re.DOTALL | re.MULTILINE)
RUNCOMMENT_RE = re.compile(r"\A\s*(?:^#[^\n]*\n)+\s*(?=import marimo\n)", re.MULTILINE)
SETUP_RE = re.compile(r"^with app\.setup:\n", re.MULTILINE)
LAYOUT_PATH_RE = re.compile(r'layout_file\s*=\s*"([^"]+)"')
CELL_RE = re.compile(r"^@app\.cell", re.MULTILINE)


class ExportError(RuntimeError):
    """Anything that should stop the pipeline with a readable message."""


# --------------------------------------------------------------------------- #
# 1. bundle
# --------------------------------------------------------------------------- #


def rewrite_header(header: str) -> str:
    """Drop the rsmodel dependency and its local path source.

    Pyodide installs from PyPI and cannot follow `{ path = "../rsmodel" }`, and
    the package is inlined below anyway.
    """
    out, in_sources = [], False
    for line in header.splitlines(keepends=True):
        stripped = line.lstrip("# ").rstrip()
        if stripped.startswith("[tool.uv.sources]"):
            in_sources = True
            continue
        if in_sources:
            if stripped.startswith("rsmodel"):
                continue
            if stripped.startswith("["):
                in_sources = False
            elif stripped == "///":
                in_sources = False
            elif stripped == "":
                continue
        if re.fullmatch(r'#\s*"rsmodel[^"]*",\s*', line.rstrip("\n")):
            continue
        out.append(line)
    return re.sub(r"(#\n)+(# ///)", r"\2", "".join(out))


def embed(name: str, source: str) -> str:
    """Render one module's source as a readable dict entry."""
    if "'''" in source:
        raise ExportError(f"{name}.py contains ''' — the r''' embedding is unsafe")
    if source.rstrip("\n").endswith("\\"):
        raise ExportError(f"{name}.py ends with a backslash — invalid in a raw string")
    return f"    {name!r}: r'''\n{source}''',\n"


def build_setup_block(notebook_name: str) -> str:
    """The `with app.setup:` block that makes `import rsmodel` work in Pyodide."""
    if not PKG_DIR.is_dir():
        raise ExportError(f"package directory not found: {PKG_DIR}")
    entries = "".join(
        embed(n, (PKG_DIR / f"{n}.py").read_text(encoding="utf-8")) for n in MODULES
    )
    return f'''with app.setup:
    # --- vendored rsmodel package (generated by tools/export_playground.py) ---
    # Do not edit here. Edit rsmodel/rsmodel/*.py and re-export.
    # Source notebook: {notebook_name}
    import sys as _sys
    import types as _types

    _RSMODEL_SOURCES = {{
{entries}    }}

    def _install_rsmodel(sources, package="rsmodel"):
        """Register the inlined sources as an importable package."""
        pkg = _types.ModuleType(package)
        pkg.__path__ = []  # marks it as a package so relative imports resolve
        pkg.__package__ = package
        _sys.modules[package] = pkg
        for name in sources:
            if name == "__init__":
                continue
            mod = _types.ModuleType(f"{{package}}.{{name}}")
            mod.__package__ = package
            _sys.modules[f"{{package}}.{{name}}"] = mod
            exec(compile(sources[name], f"<{{package}}/{{name}}.py>", "exec"), mod.__dict__)
            setattr(pkg, name, mod)
        exec(
            compile(sources["__init__"], f"<{{package}}/__init__.py>", "exec"),
            pkg.__dict__,
        )
        return pkg

    if "rsmodel" not in _sys.modules:
        _install_rsmodel(_RSMODEL_SOURCES)
    # --- end vendored rsmodel ---

'''


def bundle(notebook: Path, staging: Path) -> tuple[Path, int, int]:
    """Write the vendored notebook (+ its layout) into `staging`.

    Returns (notebook path, cell count, layout entry count).
    """
    text = notebook.read_text(encoding="utf-8")

    m = HEADER_RE.match(text)
    if not m:
        raise ExportError(f"no PEP 723 header in {notebook}")
    header, body = rewrite_header(m.group(0)), text[m.end() :]
    body = RUNCOMMENT_RE.sub("", body)  # local run instructions do not apply here

    if SETUP_RE.search(body):
        raise ExportError(
            f"{notebook.name} already has a `with app.setup:` block; "
            "merge the vendored package into it by hand"
        )

    app_m = APP_RE.search(body)
    if not app_m:
        raise ExportError(f"no `app = marimo.App(...)` statement in {notebook}")
    app_stmt = app_m.group(0)

    # Ship the layout as a sibling file rather than a data: URI. marimo's exporter
    # calls inline_layout_file(), which does Path(layout_file).read_bytes() with no
    # guard for an already-inlined URI — it would treat the base64 blob as a
    # filename and die with "File name too long". Let marimo do the inlining.
    layout_entries = 0
    lm = LAYOUT_PATH_RE.search(app_stmt)
    if lm:
        layout_src = notebook.parent / lm.group(1)
        if not layout_src.exists():
            raise ExportError(f"layout file not found: {layout_src}")
        raw = layout_src.read_bytes()
        layout_entries = len(json.loads(raw)["data"]["cells"])
        (staging / layout_src.name).write_bytes(raw)
        app_stmt = app_stmt.replace(lm.group(1), layout_src.name)

    banner = (
        "# GENERATED — do not edit; built by tools/export_playground.py\n"
        f"# Source: {notebook.relative_to(ROOT)}\n\n"
    )
    out = (
        header
        + banner
        + body[: app_m.start()]
        + app_stmt
        + "\n"
        + build_setup_block(str(notebook.relative_to(ROOT)))
        + body[app_m.end() :]
    )

    dst = staging / notebook.name
    dst.write_text(out, encoding="utf-8")
    return dst, len(CELL_RE.findall(out)), layout_entries


# --------------------------------------------------------------------------- #
# 2. export
# --------------------------------------------------------------------------- #


def export(notebook: Path, output: Path, *, show_code: bool, execute: bool) -> None:
    """Run `marimo export html-wasm` into `output`."""
    if output.exists():
        shutil.rmtree(output)  # stale assets from an older marimo are a real hazard
    output.mkdir(parents=True, exist_ok=True)

    cmd = [
        sys.executable, "-m", "marimo", "export", "html-wasm",
        "--mode", "run",
        "--show-code" if show_code else "--no-show-code",
        "-o", str(output),
        "-f",
    ]
    if execute:
        cmd.append("--execute")
    cmd.append(str(notebook))

    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise ExportError(
            "marimo export failed:\n"
            + (proc.stderr or proc.stdout or "").strip()[-2000:]
        )


# --------------------------------------------------------------------------- #
# 3. verify
# --------------------------------------------------------------------------- #


def verify(output: Path, cells: int, layout_entries: int) -> list[str]:
    """Read the exported index.html back and assert it is actually usable."""
    index = output / "index.html"
    if not index.exists():
        raise ExportError(f"no index.html in {output}")
    h = index.read_text(encoding="utf-8")
    notes: list[str] = []

    mode = re.search(r'"mode":\s*"(\w+)"', h)
    if not mode or mode.group(1) != "read":
        raise ExportError(f"expected run mode, index.html says {mode and mode.group(1)}")
    notes.append("opens in run mode")

    show = re.search(r'"showAppCode":\s*(\w+)', h)
    notes.append(f"code hidden by default: {show.group(1) if show else 'unknown'}")

    if layout_entries:
        lm = re.search(r'"layout_file":\s*"data:[^,]+,([^"]+)"', h)
        if not lm:
            raise ExportError("slides layout missing from the exported index.html")
        layout = json.loads(base64.b64decode(lm.group(1)))
        got = len(layout["data"]["cells"])
        if layout.get("type") != "slides":
            raise ExportError(f"layout type is {layout.get('type')!r}, expected 'slides'")
        if got != layout_entries:
            raise ExportError(
                f"layout has {got} entries but the source layout has {layout_entries}"
            )
        if got != cells:
            notes.append(
                f"WARNING: {got} layout entries vs {cells} cells — the layout is "
                "positional, so slides may be misassigned"
            )
        kinds = [c.get("type", "normal") for c in layout["data"]["cells"]]
        notes.append(
            f"slides layout inlined: {got} entries "
            f"({kinds.count('normal')} slides, {kinds.count('sub-slide')} sub-slides, "
            f"{kinds.count('skip')} skipped)"
        )

    if "_install_rsmodel" not in h:
        raise ExportError("rsmodel was not embedded in the exported notebook")
    notes.append("rsmodel vendored into the payload")

    if not (output / ".nojekyll").exists():
        (output / ".nojekyll").touch()
        notes.append(".nojekyll added (GitHub Pages would skip ./assets otherwise)")

    size = sum(f.stat().st_size for f in output.rglob("*") if f.is_file())
    notes.append(f"{sum(1 for _ in output.rglob('*') if _.is_file())} files, {size / 1e6:.1f} MB")
    return notes


def serve(output: Path, port: int) -> None:
    """Preview the site locally. file:// will not work — WASM needs real HTTP."""
    handler = functools.partial(
        http.server.SimpleHTTPRequestHandler, directory=str(output)
    )
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("127.0.0.1", port), handler) as httpd:
        print(f"\nserving {output} at http://127.0.0.1:{port}/  (ctrl-c to stop)")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nstopped")


DEPLOY_HINT = """
Next steps — publishing to GitHub Pages
---------------------------------------
The site is fully static and every asset path is relative, so it works both at
a user site (user.github.io) and a project site (user.github.io/repo/).

  A. GitHub Actions (recommended: nothing generated is committed)
     .github/workflows/pages.yml in this repo already does it. Enable it once
     under Settings -> Pages -> Source -> GitHub Actions, then push.

  B. Manual, no Actions
     Export straight into a committed folder and serve that:
         uv run tools/export_playground.py -o docs
         git add -f docs && git commit -m "publish site" && git push
     Then Settings -> Pages -> Source -> Deploy from a branch -> main + /docs.

Notes
  * Pages on a private repo needs a paid GitHub plan; a public repo is free.
  * The first browser load fetches Pyodide (~10-30 MB) from a CDN. Slow once,
    then cached.
  * Test locally before publishing: --serve. Opening index.html as a file://
    URL will not work.
"""


def main() -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("notebook", nargs="?", type=Path, default=DEFAULT_NOTEBOOK)
    p.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    p.add_argument("--show-code", action="store_true", help="show code in the app")
    p.add_argument(
        "--execute",
        action="store_true",
        help="run the notebook and embed outputs, so the page shows content "
        "while Pyodide boots (slower; needs the notebook's dependencies)",
    )
    p.add_argument("--serve", action="store_true", help="serve the result when done")
    p.add_argument("--port", type=int, default=8000)
    p.add_argument("--no-hint", action="store_true", help="skip the deploy notes")
    args = p.parse_args()

    notebook: Path = args.notebook
    if not notebook.exists():
        print(f"error: no such notebook: {notebook}", file=sys.stderr)
        return 1

    try:
        with tempfile.TemporaryDirectory() as tmp:
            staging = Path(tmp)
            print(f"bundling {notebook.name} + rsmodel ...")
            bundled, cells, layout_entries = bundle(notebook, staging)
            print(f"  {cells} cells, {len(MODULES)} rsmodel modules inlined")

            print(f"exporting to {args.output} ...")
            export(
                bundled,
                args.output,
                show_code=args.show_code,
                execute=args.execute,
            )

        print("verifying ...")
        for note in verify(args.output, cells, layout_entries):
            print(f"  {'! ' if note.startswith('WARNING') else 'ok '}{note}")
    except ExportError as e:
        print(f"\nerror: {e}", file=sys.stderr)
        return 1

    print(f"\ndone -> {args.output}")
    if not args.no_hint:
        print(DEPLOY_HINT)
    if args.serve:
        serve(args.output, args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
